name: test script for convert.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: make ctest; ./test_script > test_results.txt; gcov ctest-convert.c

      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/ipload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt
